import type { Project } from '../types';

const project: Project = {
  slug: 'financas-pessoais',
  order: 1,
  featured: true,
  title: {
    pt: 'Pipeline de Finanças Pessoais',
    en: 'Personal Finance Pipeline',
  },
  tagline: {
    pt: 'Extratos de dois bancos viram um data warehouse versionado, com dbt, Supabase e Metabase.',
    en: 'Statements from two banks turned into a versioned warehouse with dbt, Supabase and Metabase.',
  },
  problem: {
    pt: 'Nubank exporta OFX, Itaú exporta XLSX. A categorização era manual em planilha, sem histórico consolidado nem visão de evolução patrimonial.',
    en: 'Nubank exports OFX, Itaú exports XLSX. Categorisation was manual in a spreadsheet, with no consolidated history and no view of net worth over time.',
  },
  solution: {
    pt: 'Bot do Telegram recebe o extrato, um ingestor Python normaliza os formatos e grava no Supabase; dbt-core modela as camadas bronze, silver e gold e o GitHub Actions agenda tudo.',
    en: 'A Telegram bot receives the statement, a Python ingester normalises both formats into Supabase, dbt-core models the bronze, silver and gold layers and GitHub Actions schedules the whole run.',
  },
  result: {
    pt: 'Fluxo de caixa mensal, gastos por categoria e evolução de saldo em dashboards no Metabase, atualizados sem trabalho manual.',
    en: 'Monthly cash flow, spend by category and balance evolution in Metabase dashboards, refreshed with no manual work.',
  },
  stack: ['Python', 'dbt', 'PostgreSQL', 'Supabase', 'GitHub Actions', 'Metabase', 'SQL', 'Telegram API'],
  repoUrl: 'https://github.com/diegoscs/financas-pipeline',
  // Imagem de Open Graph — descomente quando o arquivo existir em /public/projects:
  // cover: '/projects/financas-pessoais-cover.png',
  caseStudy: {
    sections: [
      {
        heading: { pt: 'Contexto e problema', en: 'Context and problem' },
        body: {
          pt: 'Eu acompanhava minhas finanças em uma planilha. Todo mês baixava o extrato do Nubank em **OFX** e o do Itaú em **XLSX**, copiava as linhas na mão, ajustava colunas que não batiam e classificava cada transação por categoria.\n\nTrês problemas apareciam sempre: os formatos são diferentes e nenhum deles usa os mesmos nomes de coluna; lançamentos duplicados entravam quando eu reimportava um período; e não existia histórico consolidado — cada mês era uma aba isolada, então não dava para ver evolução de saldo nem comparar categorias ao longo do ano.\n\nO objetivo do projeto foi trocar esse ritual manual por um pipeline versionado, com schema único entre bancos e execução agendada.',
          en: 'I used to track my finances in a spreadsheet. Every month I downloaded the Nubank statement as **OFX** and the Itaú one as **XLSX**, pasted rows by hand, fixed columns that did not line up and tagged every transaction with a category.\n\nThree problems kept coming back: the formats differ and share no column names; duplicated entries slipped in whenever I re-imported a period; and there was no consolidated history — each month was its own isolated tab, so there was no way to see balance evolution or compare categories across the year.\n\nThe goal was to replace that manual ritual with a versioned pipeline, a single schema across banks and a scheduled run.',
        },
      },
      {
        heading: { pt: 'Arquitetura', en: 'Architecture' },
        body: {
          pt: 'O fluxo tem um único ponto de entrada — o bot do Telegram — e uma única fonte de verdade — o Postgres do Supabase. O GitHub Actions envolve o pipeline: agenda a execução, dispara a ingestão, aplica os modelos dbt e publica o resultado dos testes.',
          en: 'The flow has a single entry point — the Telegram bot — and a single source of truth — the Supabase Postgres. GitHub Actions wraps the pipeline: it schedules the run, triggers ingestion, applies the dbt models and publishes test results.',
        },
        diagram: 'financas-architecture',
      },
      {
        heading: { pt: 'Camadas medallion', en: 'Medallion layers' },
        body: {
          pt: '**Bronze — o extrato como veio.** Nada é corrigido aqui. Uma linha de OFX do Nubank entra com `dtposted`, `trnamt` e `memo` exatamente como o banco escreveu, junto com o nome do arquivo, o banco de origem e o timestamp de ingestão. Se a leitura estiver errada, dá para reprocessar sem pedir o extrato de novo.\n\n**Silver — transações normalizadas e deduplicadas.** Aqui os dois bancos passam a falar a mesma língua: `transaction_date`, `description`, `amount` (negativo para saída, positivo para entrada), `account`, `bank`. Descrições viram caixa alta sem acento e sem espaço duplicado, valores viram `numeric(14,2)` e cada transação ganha uma chave determinística de data + conta + valor + descrição normalizada, que é o que elimina a duplicata quando o mesmo período é enviado duas vezes.\n\n**Gold — fatos e dimensões prontos para consumo.** `fct_transactions` ligada a `dim_category` e `dim_account`, mais as agregações que o dashboard consome direto: gastos por categoria no mês, fluxo de caixa mensal (entradas, saídas, líquido) e evolução de saldo acumulado por conta.',
          en: '**Bronze — the statement exactly as it arrived.** Nothing is fixed here. A Nubank OFX row lands with `dtposted`, `trnamt` and `memo` written the way the bank wrote them, alongside the source file name, the source bank and the ingestion timestamp. If parsing was wrong, I can reprocess without asking for the statement again.\n\n**Silver — normalised, deduplicated transactions.** This is where both banks start speaking the same language: `transaction_date`, `description`, `amount` (negative for outflow, positive for inflow), `account`, `bank`. Descriptions are upper-cased, stripped of accents and collapsed whitespace, amounts become `numeric(14,2)`, and every transaction gets a deterministic key of date + account + amount + normalised description — which is what removes the duplicate when the same period is uploaded twice.\n\n**Gold — facts and dimensions ready to consume.** `fct_transactions` joined to `dim_category` and `dim_account`, plus the aggregates the dashboard reads directly: spend by category per month, monthly cash flow (in, out, net) and running balance evolution per account.',
        },
      },
      {
        heading: { pt: 'Decisões técnicas', en: 'Technical decisions' },
        body: {
          pt: '**dbt-core em vez de scripts SQL soltos.** A transformação já eram uns dez arquivos `.sql` executados numa ordem que só existia na minha cabeça. Com dbt eu ganhei o grafo de dependências pelo `ref()`, testes declarativos (`unique` e `not_null` na chave da silver) e documentação gerada junto do código. E a mesma lógica que roda local roda no CI, sem adaptação.\n\n**Supabase em vez de Postgres local.** O banco precisava estar acessível de fora da minha máquina: o runner do GitHub Actions escreve nele e o Metabase lê dele. Um Postgres no notebook obrigaria a manter a máquina ligada. O Supabase entrega Postgres gerenciado, backup e credenciais de conexão sem operar infraestrutura.\n\n**Telegram em vez de pasta monitorada.** Uma pasta sincronizada só funciona no computador onde ela está montada. O extrato costuma chegar quando eu abro o app do banco no celular — mandar o arquivo para o bot é o caminho mais curto entre baixar e ingerir, e ainda me devolve confirmação de quantas linhas entraram.\n\n**GitHub Actions como orquestrador.** Um workflow com `schedule` (cron diário) e `workflow_dispatch` para rodar sob demanda. Ele instala as dependências, executa o ingestor, roda `dbt build` (modelos e testes na mesma passada) e falha ruidosamente se um teste quebrar. As credenciais ficam em GitHub Secrets, nenhum segredo no repositório.',
          en: '**dbt-core instead of loose SQL scripts.** The transformation was already about ten `.sql` files run in an order that only existed in my head. dbt gave me the dependency graph through `ref()`, declarative tests (`unique` and `not_null` on the silver key) and docs generated next to the code. The same logic runs locally and in CI with no adaptation.\n\n**Supabase instead of a local Postgres.** The database had to be reachable from outside my machine: the GitHub Actions runner writes to it and Metabase reads from it. A Postgres on my laptop would mean keeping the laptop on. Supabase gives managed Postgres, backups and connection credentials without running infrastructure.\n\n**Telegram instead of a watched folder.** A synced folder only works on the machine where it is mounted. Statements usually show up when I open the banking app on my phone — sending the file to a bot is the shortest path from download to ingestion, and it replies telling me how many rows landed.\n\n**GitHub Actions as the orchestrator.** One workflow with `schedule` (daily cron) and `workflow_dispatch` for on-demand runs. It installs dependencies, runs the ingester, runs `dbt build` (models and tests in one pass) and fails loudly when a test breaks. Credentials live in GitHub Secrets; no secret is committed.',
        },
      },
      {
        heading: {
          pt: 'Model dbt: normalização e deduplicação (silver)',
          en: 'dbt model: normalisation and deduplication (silver)',
        },
        body: {
          pt: 'A silver é onde Nubank e Itaú convergem para um schema só. Cada banco tem um CTE de normalização e o `row_number` do fim resolve reenvios do mesmo período.',
          en: 'Silver is where Nubank and Itaú converge into a single schema. Each bank gets its own normalisation CTE, and the trailing `row_number` resolves re-uploads of the same period.',
        },
        code: {
          language: 'sql',
          caption: {
            pt: 'models/silver/slv_transactions.sql — trecho ilustrativo',
            en: 'models/silver/slv_transactions.sql — illustrative excerpt',
          },
          content: [
            '-- TODO: substituir pelo código real',
            "{{ config(materialized='incremental', unique_key='transaction_key') }}",
            '',
            '-- Nubank chega em OFX: data ISO, valor já com sinal, descrição em "memo"',
            'with nubank as (',
            '    select',
            "        'nubank'                          as bank,",
            '        raw.account_id                    as account,',
            '        raw.dtposted::date                as transaction_date,',
            '        raw.trnamt::numeric(14,2)         as amount,',
            '        raw.memo                          as description_raw',
            "    from {{ ref('brz_nubank_ofx') }} as raw",
            '),',
            '',
            '-- Itaú chega em XLSX: data dd/mm/aaaa e valor como texto com vírgula decimal',
            'itau as (',
            '    select',
            "        'itau'                            as bank,",
            '        raw.conta                         as account,',
            "        to_date(raw.data, 'DD/MM/YYYY')   as transaction_date,",
            "        replace(replace(raw.valor, '.', ''), ',', '.')::numeric(14,2) as amount,",
            '        raw.lancamento                    as description_raw',
            "    from {{ ref('brz_itau_xlsx') }} as raw",
            '),',
            '',
            'unioned as (',
            '    select * from nubank',
            '    union all',
            '    select * from itau',
            '),',
            '',
            'normalized as (',
            '    select',
            '        bank,',
            '        account,',
            '        transaction_date,',
            '        amount,',
            '        -- caixa alta, sem acento e sem espaço duplicado: a mesma compra',
            '        -- descrita de formas levemente diferentes vira a mesma string',
            "        regexp_replace(upper(unaccent(description_raw)), '\\s+', ' ', 'g') as description,",
            "        case when amount < 0 then 'outflow' else 'inflow' end as direction",
            '    from unioned',
            '    where amount is not null',
            '      and transaction_date is not null',
            '),',
            '',
            'deduplicated as (',
            '    select',
            '        *,',
            '        -- chave determinística: reenviar o mesmo extrato gera a mesma chave',
            '        md5(',
            "            transaction_date::text || '|' || account || '|' ||",
            "            amount::text || '|' || description",
            '        ) as transaction_key,',
            '        row_number() over (',
            '            partition by transaction_date, account, amount, description',
            '            order by bank',
            '        ) as rn',
            '    from normalized',
            ')',
            '',
            'select',
            '    transaction_key,',
            '    bank,',
            '    account,',
            '    transaction_date,',
            '    description,',
            '    amount,',
            '    direction',
            'from deduplicated',
            'where rn = 1',
            '',
            '{% if is_incremental() %}',
            "  and transaction_date >= (select coalesce(max(transaction_date), '1900-01-01') from {{ this }})",
            '{% endif %}',
          ].join('\n'),
        },
      },
      {
        heading: { pt: 'Parser de OFX em Python', en: 'OFX parser in Python' },
        body: {
          pt: 'O ingestor recebe o arquivo do bot e devolve linhas prontas para a bronze. OFX é SGML, não XML válido, então o parser trabalha em cima das tags `<STMTTRN>` sem depender de um parser estrito.',
          en: 'The ingester takes the file from the bot and returns rows ready for bronze. OFX is SGML rather than valid XML, so the parser works over the `<STMTTRN>` tags without relying on a strict parser.',
        },
        code: {
          language: 'python',
          caption: {
            pt: 'ingestion/parsers/ofx.py — trecho ilustrativo',
            en: 'ingestion/parsers/ofx.py — illustrative excerpt',
          },
          content: [
            '# TODO: substituir pelo código real',
            'import re',
            'from dataclasses import dataclass',
            'from datetime import date, datetime',
            'from decimal import Decimal',
            'from typing import Iterator',
            '',
            '# OFX é SGML: as tags de valor não são fechadas, então regex é mais',
            '# confiável aqui do que um parser XML estrito.',
            'TRANSACTION_BLOCK = re.compile(r"<STMTTRN>(.*?)</STMTTRN>", re.DOTALL | re.IGNORECASE)',
            'FIELD = re.compile(r"<([A-Z]+)>([^<\\r\\n]*)", re.IGNORECASE)',
            '',
            '',
            '@dataclass(frozen=True)',
            'class RawTransaction:',
            '    """Linha da camada bronze: o extrato como veio, sem correção."""',
            '    account_id: str',
            '    dtposted: date',
            '    trnamt: Decimal',
            '    memo: str',
            '    source_file: str',
            '',
            '',
            'def _parse_ofx_date(value: str) -> date:',
            '    # OFX traz YYYYMMDD, às vezes com hora e fuso colados: 20250131120000[-3:BRT]',
            '    return datetime.strptime(value.strip()[:8], "%Y%m%d").date()',
            '',
            '',
            'def parse_ofx(content: str, source_file: str) -> Iterator[RawTransaction]:',
            '    """Extrai as transações de um extrato OFX do Nubank.',
            '',
            '    Não normaliza nada de propósito: normalização é responsabilidade da',
            '    camada silver, para que a bronze continue reprocessável.',
            '    """',
            '    account_id = _extract_first(content, "ACCTID") or "unknown"',
            '',
            '    for block in TRANSACTION_BLOCK.findall(content):',
            '        fields = {tag.upper(): value.strip() for tag, value in FIELD.findall(block)}',
            '',
            '        # Sem data ou sem valor a linha não é utilizável; ignora e segue.',
            '        if "DTPOSTED" not in fields or "TRNAMT" not in fields:',
            '            continue',
            '',
            '        yield RawTransaction(',
            '            account_id=account_id,',
            '            dtposted=_parse_ofx_date(fields["DTPOSTED"]),',
            '            trnamt=Decimal(fields["TRNAMT"]),',
            '            # MEMO é o campo mais preenchido; NAME é o fallback do banco',
            '            memo=fields.get("MEMO") or fields.get("NAME", ""),',
            '            source_file=source_file,',
            '        )',
            '',
            '',
            'def _extract_first(content: str, tag: str) -> str | None:',
            '    match = re.search(rf"<{tag}>([^<\\r\\n]*)", content, re.IGNORECASE)',
            '    return match.group(1).strip() if match else None',
          ].join('\n'),
        },
      },
      {
        heading: { pt: 'Dashboards no Metabase', en: 'Metabase dashboards' },
        body: {
          pt: 'As tabelas gold alimentam três visões: fluxo de caixa mensal, gastos por categoria e evolução de saldo.',
          en: 'The gold tables feed three views: monthly cash flow, spend by category and balance evolution.',
        },
        image: {
          src: '/projects/financas-metabase-overview.png',
          alt: {
            pt: 'Dashboard do Metabase com fluxo de caixa mensal e gastos por categoria',
            en: 'Metabase dashboard showing monthly cash flow and spend by category',
          },
        },
      },
      {
        heading: { pt: 'Evolução de saldo', en: 'Balance evolution' },
        body: {
          pt: 'Saldo acumulado por conta ao longo dos meses, construído sobre a agregação da camada gold.',
          en: 'Running balance per account across months, built on the gold-layer aggregate.',
        },
        image: {
          src: '/projects/financas-metabase-saldo.png',
          alt: {
            pt: 'Gráfico de linha com a evolução do saldo acumulado por conta',
            en: 'Line chart showing running balance evolution per account',
          },
        },
      },
      {
        heading: { pt: 'Resultados e aprendizados', en: 'Results and lessons' },
        body: {
          pt: 'O que era uma tarde de planilha por mês virou um pipeline versionado que roda sozinho: o extrato vai para o bot, o Actions dispara no horário e o dashboard já está atualizado quando eu abro. O ganho maior não foi tempo, foi confiança — os testes do dbt quebram o build quando a chave da silver duplica, então eu descubro o problema antes do gráfico.\n\nO que eu faria diferente: começaria pela silver com schema fechado desde o primeiro dia, em vez de deixar cada banco com colunas próprias e resolver depois; e teria escrito os testes junto do primeiro model, não depois do primeiro bug. Também tiraria a categorização de regras `case when` espalhadas e colocaria em uma tabela seed de mapeamento — cadeia de `case when` cresce mal.',
          en: 'What used to be an afternoon of spreadsheet work each month is now a versioned pipeline that runs on its own: the statement goes to the bot, Actions fires on schedule and the dashboard is already current when I open it. The real gain was not time but confidence — dbt tests break the build when the silver key duplicates, so I find the problem before the chart does.\n\nWhat I would do differently: start from a locked silver schema on day one instead of letting each bank keep its own columns and reconciling later; and write the tests alongside the first model rather than after the first bug. I would also move categorisation out of scattered `case when` rules into a seed mapping table — those chains scale badly.',
        },
      },
    ],
  },
};

export default project;
